version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /examples/maven/deepl-test-app
    schedule:
      interval: weekly