# Note: This GitLab CI configuration is used for internal testing, users can ignore it.
include:
  - project: '${CI_PROJECT_NAMESPACE}/ci-libs-for-client-libraries'
    file:
      - '/${CI_PROJECT_NAME}/.gitlab-ci.yml'

# Global --------------------------

image: openjdk:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - check
  - build
  - test
  - publish

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

# stage: check ----------------------

spotless:
  stage: check
  script: ./gradlew spotlessCheck

# stage: build ----------------------

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - deepl-java/build/

# stage: test -------------------------

test:
  stage: test
  extends: .test
  parallel:
    matrix:
      - DOCKER_IMAGE: "openjdk:18"
      - DOCKER_IMAGE: "openjdk:8"
        USE_MOCK_SERVER: "use mock server"
      - DOCKER_IMAGE: "openjdk:11"
        USE_MOCK_SERVER: "use mock server"
      - DOCKER_IMAGE: "openjdk:17"
        USE_MOCK_SERVER: "use mock server"
      - DOCKER_IMAGE: "openjdk:18"
        USE_MOCK_SERVER: "use mock server"
      - DOCKER_IMAGE: "openjdk:19"
        USE_MOCK_SERVER: "use mock server"
      - DOCKER_IMAGE: "openjdk:20"
        USE_MOCK_SERVER: "use mock server"
  image: ${DOCKER_IMAGE}
  script:
    - >
      if [[ ! -z "${USE_MOCK_SERVER}" ]]; then
        echo "Using mock server"
        export DEEPL_SERVER_URL=http://deepl-mock:3000
        export DEEPL_MOCK_SERVER_PORT=3000
        export DEEPL_PROXY_URL=http://deepl-mock:3001
        export DEEPL_MOCK_PROXY_SERVER_PORT=3001
      fi
    - ./gradlew test
  artifacts:
    paths:
      - deepl-java/build/reports/tests/test
    reports:
      junit:
        - deepl-java/build/reports/tests/test/index.html
    when: always

# stage: publish -------------------------

publish:
  stage: publish
  extends: .publish
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  script:
    - ./gradlew publish

